#!/usr/bin/env python
"""Build Java handler from source"""

from argparse import ArgumentParser, FileType
from subprocess import call

parser = ArgumentParser(description=__doc__)
parser.add_argument('file', help='java source file', type=FileType())
parser.add_argument('--name', '-n', help='image name', default='jhandler')
parser.add_argument('--handler', '-H', help='handler name', default='Handler')

args = parser.parse_args()

cmd = [
    'nuctl', 'build',
    '--no-pull',
    '-v',
    '--no-cleanup',
    '--runtime', 'java',
    '-p', args.file.name,
    args.name,
]
raise SystemExit(call(cmd))
