#!/bin/bash
# Install go dependencies for iguazio

set -e
set -x

go get github.com/v3io/v3io-go-http
go get github.com/nuclio/logger
go get github.com/nuclio/nuclio-sdk-go
go get github.com/nuclio/amqp
