#!/bin/bash
"""Provision GCE CI machine"""

gcloud beta compute \
    --project "pivotal-gearbox-188814" \
    instances create "nuclio-ci" \
    --zone "us-east1-b"\
    --machine-type "n1-highcpu-16"\
    --subnet "default"\
    --maintenance-policy "MIGRATE" \
    --service-account "719178565695-compute@developer.gserviceaccount.com" \
    --scopes "https://www.googleapis.com/auth/devstorage.read_only","https://www.googleapis.com/auth/logging.write","https://www.googleapis.com/auth/monitoring.write","https://www.googleapis.com/auth/servicecontrol","https://www.googleapis.com/auth/service.management.readonly","https://www.googleapis.com/auth/trace.append" \
    --min-cpu-platform "Automatic" \
    --image "ubuntu-1604-xenial-v20180306" \
    --image-project "ubuntu-os-cloud" \
    --boot-disk-size "40" \
    --boot-disk-type "pd-ssd" \
    --boot-disk-device-name "nuclio-ci"
