#!/usr/bin/env python
# Run the java wrapper jar

from os.path import dirname, abspath
from subprocess import call
from argparse import ArgumentParser

here = dirname(abspath(__file__))

parser = ArgumentParser(description=__doc__)
parser.add_argument(
    '-p', '--port', type=int, help='server port', default=8080)
args = parser.parse_args()

# Assume we're running from nuclio root
wrapper_jar = 'pkg/processor/runtime/java/target/nuclio-java-warpper.jar'
handler_jar = \
    '{}/java-handler/target/nuclio-test-handler-1.0-SNAPSHOT.jar'.format(here)


cmd = [
    'java', '-jar', wrapper_jar,
    '-jar', handler_jar,
    '-handler', 'ReverseEventHandler',
    '-port', str(args.port),
    '-verbose',
]

exit(call(cmd))
