#!/usr/bin/env python
# Run the java wrapper jar

from argparse import ArgumentParser, FileType
from os.path import abspath, dirname
from subprocess import call

from java_build import build_wrapper

here = dirname(abspath(__file__))

default_jar = f'{here}/java-handler/build/libs/nuclio-test-handler.jar'
default_handler = 'ReverseEventHandler'

parser = ArgumentParser(description=__doc__)
parser.add_argument(
    '-p', '--port', type=int, help='server port', default=8080)
parser.add_argument(
    '-j', '--jar', help='jar file name', type=FileType(), default=default_jar)
parser.add_argument(
    '-H', '--handler', help='handler name', default=default_handler)
args = parser.parse_args()

jar_name = build_wrapper(args.jar.name)
if not jar_name:
    raise SystemExit('error: cannot build')

cmd = [
    'java',
    '-jar', jar_name,
    '-handler', args.handler,
    '-port', str(args.port),
    '-verbose',
]

raise SystemExit(call(cmd))
