#!/usr/bin/env python
# Run the java processor

from os.path import dirname, abspath, basename
from os import environ
from subprocess import call
from argparse import ArgumentParser, FileType

here = dirname(abspath(__file__))

default_jar = '{}./java-handler/build/libs/java-handler.jar'.format(here)
default_handler = 'ReverseEventHandler'

parser = ArgumentParser(description=__doc__)
parser.add_argument(
    '-j', '--jar', help='jar file name', type=FileType(), default=default_jar)
parser.add_argument(
    '-H', '--handler', help='handler name', default=default_handler)
parser.add_argument(
    '-w', '--max-workers', help='number of workers', default=1, type=int)
args = parser.parse_args()

jar_file = abspath(args.jar.name)
handler_name = args.handler

cfg = '''
meta:
  name: java-reverser
spec:
  runtime: java
  handler: {}:{}
  triggers:
    incrementor_http:
      maxWorkers: {}
      kind: http
'''.format(basename(jar_file), handler_name. args.max_workers)

cfg_file = '/tmp/java-handler.yaml'
with open(cfg_file, 'w') as out:
    out.write(cfg)

env = environ.copy()
# Assume we're running from nuclio root
env['NUCLIO_WRAPPER_JAR'] = \
    'pkg/processor/runtime/java/build/libs/nuclio-java-wrapper.jar'
env['NUCLIO_HANDLER_DIR'] = dirname(jar_file)

retval = call(['./processor', '-config', cfg_file], env=env)
exit(retval)
