#!/usr/bin/env python
# Run the java processor

from os.path import dirname, abspath
from os import environ
from subprocess import call
from argparse import ArgumentParser

here = dirname(abspath(__file__))

# Support --help, -h
parser = ArgumentParser(description='Run java processor')
parser.parse_args()

env = environ.copy()

# Assume we're running from nuclio root
env['NUCLIO_WRAPPER_JAR'] = \
    'pkg/processor/runtime/java/target/nuclio-java-warpper.jar'
env['NUCLIO_HANDLER_DIR'] = '{}/java-handler/target'.format(here)

cfg_file = '{}/java-handler/function.yaml'.format(here)

retval = call(['./processor', '-config', cfg_file])
