#!/usr/bin/env python
"""Update CI host IP on"""

import re
from io import StringIO
from argparse import ArgumentParser
from os.path import expanduser

cfg_file = expanduser('~/.ssh/config')


parser = ArgumentParser(description=__doc__)
parser.add_argument('ip', help='IP to set')
args = parser.parse_args()

buf = StringIO()
in_host = False
with open(cfg_file) as fp:
    for line in fp:
        match = re.search('^Host\s+([0-9A-Z_a-z-]+)', line)
        if match:
            in_host = match.group(1) == 'nuclio-ci'
        elif in_host:
            match = re.search('^\s+HostName\s+', line)
            if match:
                line = f'{match.group()}{args.ip}\n'
        buf.write(line)

with open(cfg_file, 'w') as out:
    out.write(buf.getvalue())
