#!/usr/bin/env python
"""Update the Nuclio Java SDK jar in all project"""

from argparse import ArgumentParser, FileType
from glob import iglob
from os.path import abspath, basename
from shutil import copy

parser = ArgumentParser(description=__doc__)
parser.add_argument('sdk_jar', help='path to SDK jar', type=FileType())

args = parser.parse_args()
jar_path = abspath(args.sdk_jar.name)
matches = iglob(f'./**/{basename(jar_path)}', recursive=True)
nfiles = 0
for nfiles, local_jar in enumerate(matches, 1):
    print(local_jar)
    copy(jar_path, local_jar)

print(f'Total of {nfiles} updated')
